# Activations

# ReLU Activation Function

Pseudocode for the above is simply:

```python
import numpy as np

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []

for i in inputs:
    output.append(np.maximum(i, 0))
```

In [2]:
import numpy as np


class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Calculate output values from inputs, weights, and biases
        self.output = np.dot(inputs, self.weights) + self.biases


class ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

## Testing

In [3]:
from nnfs.datasets import spiral_data


X, y = spiral_data(samples=100, classes=3)

dense1 = LayerDense(2, 3)

activation1 = ReLU()

dense1.forward(X)

activation1.forward(dense1.output)

print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.16242288e-05 0.00000000e+00]
 [0.00000000e+00 2.47995533e-05 0.00000000e+00]
 [0.00000000e+00 1.10183500e-04 0.00000000e+00]
 [0.00000000e+00 3.27072690e-04 0.00000000e+00]]
